# Generated by Django 5.1.1 on 2025-01-28 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aufgabe_neu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unternehmen_kategorie', models.IntegerField()),
                ('fragentyp', models.IntegerField()),
                ('fragentyp_text', models.CharField(max_length=255)),
                ('mailtext', models.TextField()),
                ('frage', models.TextField()),
                ('bezugswert', models.FloatField()),
                ('min_wert', models.FloatField(blank=True, null=True)),
                ('max_wert', models.FloatField(blank=True, null=True)),
                ('nutzungsdauer', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AufgabeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontoname', models.CharField(max_length=255)),
                ('soll_haben', models.CharField(choices=[('Soll', 'Soll'), ('Haben', 'Haben')], max_length=50)),
                ('betrag', models.FloatField()),
                ('monatsangabe', models.BooleanField(default=False)),
                ('monat', models.IntegerField(blank=True, null=True)),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='posts.aufgabe_neu')),
            ],
        ),
        migrations.CreateModel(
            name='Buchung',
            fields=[
                ('buchung_id', models.AutoField(primary_key=True, serialize=False)),
                ('freischaltung', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('gelöst', 'Gelöst'), ('falsch', 'Falsch'), ('offen', 'Offen')], default='offen', max_length=20)),
                ('abgeschlossen_datum', models.DateField(blank=True, null=True)),
                ('antwort_konten_soll', models.JSONField(blank=True, null=True)),
                ('antwort_konten_haben', models.JSONField(blank=True, null=True)),
                ('antwort_betrag_soll', models.JSONField(blank=True, null=True)),
                ('antwort_betrag_haben', models.JSONField(blank=True, null=True)),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.aufgabe_neu')),
                ('ersteller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ersteller', to=settings.AUTH_USER_MODEL)),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NutzerAufgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soll_konto', models.CharField(max_length=255)),
                ('haben_konto', models.CharField(max_length=255)),
                ('betrag', models.FloatField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geloest', models.BooleanField(default=False)),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.aufgabe_neu')),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unternehmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('author', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
