# Generated by Django 5.1.1 on 2024-10-22 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aufgabe',
            fields=[
                ('aufgabentext', models.TextField()),
                ('loesung_haben', models.JSONField(blank=True, null=True)),
                ('loesung_soll', models.JSONField(blank=True, null=True)),
                ('multiple_choice_antworten', models.JSONField(blank=True, null=True)),
                ('richtige_antwort', models.TextField(blank=True, null=True)),
                ('aufgabentyp', models.CharField(choices=[('buchungssatz', 'Buchungssatz'), ('multiple_choice', 'Multiple Choice'), ('texteingabe', 'Texteingabe')], max_length=50)),
                ('erstellungsdatum', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.kategorie')),
            ],
        ),
    ]
