# Generated by Django 5.1 on 2024-09-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='baner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
