# Generated by Django 5.1.1 on 2024-10-24 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_kategorie_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AufgabeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('non', 'Nicht bearbeitet'), ('pending', 'Falsch eingereicht'), ('complete', 'Richtig eingereicht')], default='non', max_length=10)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aufgaben_status', to='posts.aufgabe')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aufgaben_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'aufgabe')},
            },
        ),
    ]
