# Generated by Django 5.1.1 on 2025-01-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_aufgabenkategorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unternehmen',
            name='author',
        ),
    ]
