# Generated by Django 5.1.1 on 2025-01-29 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_unternehmen_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='fragentyp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.aufgabenkategorie'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='unternehmen_kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.unternehmen'),
        ),
    ]
