# Generated by Django 5.1.1 on 2024-10-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_aufgabestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabestatus',
            name='freigeschaltet',
            field=models.BooleanField(default=True),
        ),
    ]
