# Generated by Django 5.1.1 on 2025-01-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_aufgabestatus_freigeschaltet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aufgabe_neu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unternehmen_kategorie', models.IntegerField()),
                ('fragentyp', models.IntegerField()),
                ('fragentyp_text', models.CharField(max_length=255)),
                ('mail_text', models.TextField()),
                ('frage', models.TextField()),
                ('variablen', models.JSONField()),
                ('variablen_bereich', models.JSONField()),
                ('konten_haben', models.JSONField()),
                ('konten_soll', models.JSONField()),
                ('logik_haben', models.JSONField()),
                ('logik_soll', models.JSONField()),
            ],
        ),
    ]
