# Generated by Django 5.1.1 on 2025-01-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_aufgabe_neu_fragentyp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchung',
            name='korrekturbuchung',
            field=models.BooleanField(default=False),
        ),
    ]
