# Generated by Django 5.1.1 on 2025-01-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_aufgabe_neu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aufgabe_neu',
        ),
    ]
