# Generated by Django 5.1.1 on 2025-02-10 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_buchung_korrekturbuchung'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betreff', models.CharField(max_length=255)),
                ('mailtext', models.TextField()),
                ('von', models.CharField(default='system@secure-net.de', max_length=100)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('nicht bearbeitet', 'Nicht bearbeitet'), ('bearbeitet', 'Bearbeitet')], default='nicht bearbeitet', max_length=50)),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.aufgabe_neu')),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
