# Generated by Django 5.1.1 on 2024-10-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_aufgabe'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='aufgabentyp',
            field=models.CharField(choices=[('buchungssatz', 'Buchungssatz'), ('multiple_choice', 'Multiple Choice'), ('texteingabe', 'Texteingabe')], default='buchungssatz', max_length=50),
            preserve_default=False,
        ),
    ]
