# Generated by Django 5.1.1 on 2024-10-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_aufgabe_aufgabentyp'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='multiple_choice_antworten',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aufgabe',
            name='richtige_antwort',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='loesung_haben',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='loesung_soll',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
