# Generated by Django 5.1.1 on 2025-01-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_delete_aufgabe_neu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aufgabe_neu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unternehmen_kategorie', models.IntegerField()),
                ('fragentyp', models.IntegerField()),
                ('fragentyp_text', models.CharField(max_length=255)),
                ('mailtext', models.TextField()),
                ('frage', models.TextField()),
                ('bezugswert', models.FloatField()),
                ('min_wert', models.FloatField(blank=True, null=True)),
                ('max_wert', models.FloatField(blank=True, null=True)),
                ('nutzungsdauer', models.IntegerField(blank=True, null=True)),
                ('kontoname', models.CharField(max_length=255)),
                ('soll_haben', models.CharField(choices=[('Soll', 'Soll'), ('Haben', 'Haben')], max_length=50)),
                ('betrag', models.FloatField()),
                ('monatsangabe', models.BooleanField(default=False)),
                ('monat', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
