# Generated by Django 5.1.1 on 2025-02-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='bearbeitet_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
