# Generated by Django 5.1.1 on 2024-10-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_aufgabe_multiple_choice_antworten_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
