# Generated by Django 5.1.1 on 2025-02-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_mail_bearbeitet_am'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='bearbeitet_am',
        ),
    ]
