# Generated by Django 5.1.1 on 2025-01-14 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_aufgabe_neu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufgabe_neu',
            name='betrag',
        ),
        migrations.RemoveField(
            model_name='aufgabe_neu',
            name='kontoname',
        ),
        migrations.RemoveField(
            model_name='aufgabe_neu',
            name='monat',
        ),
        migrations.RemoveField(
            model_name='aufgabe_neu',
            name='monatsangabe',
        ),
        migrations.RemoveField(
            model_name='aufgabe_neu',
            name='soll_haben',
        ),
        migrations.CreateModel(
            name='AufgabeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontoname', models.CharField(max_length=255)),
                ('soll_haben', models.CharField(choices=[('Soll', 'Soll'), ('Haben', 'Haben')], max_length=50)),
                ('betrag', models.FloatField()),
                ('monatsangabe', models.BooleanField(default=False)),
                ('monat', models.IntegerField(blank=True, null=True)),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='posts.aufgabe_neu')),
            ],
        ),
    ]
