# Generated by Django 5.1.1 on 2025-02-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_mail_bearbeitet_am'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchung',
            name='status',
            field=models.CharField(choices=[('offen', 'Offen'), ('bearbeitet', 'Bearbeitet'), ('korrekt', 'Korrekt')], default='offen', max_length=20),
        ),
    ]
