# Generated by Django 5.1.1 on 2025-01-20 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_aufgabe_neu_betrag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buchung',
            fields=[
                ('buchung_id', models.AutoField(primary_key=True, serialize=False)),
                ('freischaltung', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('gelöst', 'Gelöst'), ('falsch', 'Falsch'), ('offen', 'Offen')], default='offen', max_length=20)),
                ('abgeschlossen_datum', models.DateField(blank=True, null=True)),
                ('antwort_konten_soll', models.JSONField(blank=True, null=True)),
                ('antwort_konten_haben', models.JSONField(blank=True, null=True)),
                ('antwort_betrag_soll', models.JSONField(blank=True, null=True)),
                ('antwort_betrag_haben', models.JSONField(blank=True, null=True)),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.aufgabe_neu')),
                ('ersteller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ersteller', to=settings.AUTH_USER_MODEL)),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
