# Generated by Django 5.1.1 on 2025-01-20 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_buchung'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutzerAufgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soll_konto', models.CharField(max_length=255)),
                ('haben_konto', models.CharField(max_length=255)),
                ('betrag', models.FloatField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geloest', models.BooleanField(default=False)),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.aufgabe_neu')),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
