# Generated by Django 5.1.1 on 2025-02-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_buchung_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchung',
            name='versuch',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
