# Generated by Django 5.1.1 on 2024-10-16 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_kategorie_alter_aufgabe_kategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='kategorie_alt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.kategorie'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='kategorie',
            field=models.CharField(max_length=100),
        ),
    ]
