# Generated by Django 5.1.1 on 2024-10-16 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_aufgabe_kategorie_alt_alter_aufgabe_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufgabe',
            name='kategorie_alt',
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.kategorie'),
        ),
    ]
