# Generated by Django 5.1.1 on 2025-01-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_nutzeraufgabe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchung',
            name='antwort_betrag_haben',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='antwort_betrag_soll',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
