# Generated by Django 5.1.1 on 2025-02-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_buchung_versuch'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='versuch',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
