# Generated by Django 5.1.1 on 2025-01-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_buchung_antwort_betrag_haben_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchung',
            name='antwort_betrag_haben',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='antwort_betrag_soll',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
