# Generated by Django 5.1.1 on 2024-10-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_aufgabe_kategorie_alt_alter_aufgabe_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufgabe',
            name='author',
        ),
    ]
