# Generated by Django 5.1.1 on 2025-02-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_konto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutzeraufgabe',
            name='geloest',
        ),
        migrations.AddField(
            model_name='nutzeraufgabe',
            name='bearbeitungsstand',
            field=models.CharField(choices=[('offen', 'Offen'), ('bearbeitet', 'Bearbeitet'), ('korrekt', 'Korrekt')], default='offen', max_length=20),
        ),
    ]
