# Generated by Django 5.1.1 on 2025-01-22 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_buchung_antwort_betrag_haben_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kategorie',
            new_name='Aufgabenkategorie',
        ),
        migrations.RenameField(
            model_name='aufgabe_neu',
            old_name='fragentyp_text',
            new_name='aufgabentyp_text',
        ),
        migrations.RemoveField(
            model_name='aufgabe_neu',
            name='fragentyp',
        ),
        migrations.AddField(
            model_name='aufgabe_neu',
            name='aufgabenkategorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.aufgabenkategorie'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Unternehmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('author', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='unternehmen_kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.unternehmen'),
        ),
    ]
