# Generated by Django 5.1.1 on 2025-01-22 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_rename_kategorie_aufgabenkategorie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unternehmen',
            new_name='Kategorie',
        ),
        migrations.RemoveField(
            model_name='aufgabe_neu',
            name='aufgabenkategorie',
        ),
        migrations.RenameField(
            model_name='aufgabe_neu',
            old_name='aufgabentyp_text',
            new_name='fragentyp_text',
        ),
        migrations.AddField(
            model_name='aufgabe_neu',
            name='fragentyp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='unternehmen_kategorie',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Aufgabenkategorie',
        ),
    ]
