# Generated by Django 5.1.1 on 2024-10-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_aufgabe_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufgabe',
            name='author',
        ),
    ]
