# Generated by Django 5.1.1 on 2025-02-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_remove_nutzeraufgabe_geloest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='absender_adresse',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mail',
            name='absender_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
