# Generated by Django 5.1.1 on 2025-02-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_mail_absender_adresse_mail_absender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='konto',
            name='kategorie',
            field=models.CharField(blank=True, choices=[('Bestandskonto', 'Bestandskonto'), ('Erfolgskonto', 'Erfolgskonto')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='konto',
            name='unterkategorie',
            field=models.CharField(blank=True, choices=[('Aktiva', 'Aktiva'), ('Passiva', 'Passiva'), ('Aufwand', 'Aufwand'), ('Ertrag', 'Ertrag')], max_length=20, null=True),
        ),
    ]
