# Generated by Django 5.1.1 on 2025-02-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_konto_kategorie_konto_unterkategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='konto',
            name='eins',
            field=models.CharField(blank=True, choices=[('Aktiva', 'Aktiva'), ('Passiva', 'Passiva'), ('Aufwand', 'Aufwand'), ('Ertrag', 'Ertrag')], max_length=20, null=True),
        ),
    ]
