# Generated by Django 5.1.1 on 2025-02-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_konto_eins'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe_neu',
            name='feedback_betrag_falsch',
            field=models.TextField(blank=True, help_text='Feedback, wenn der Betrag falsch ist.', null=True),
        ),
        migrations.AddField(
            model_name='aufgabe_neu',
            name='feedback_konto_falsch',
            field=models.TextField(blank=True, help_text='Feedback, wenn ein falsches Konto gewählt wurde.', null=True),
        ),
    ]
