# Generated by Django 5.1.1 on 2025-02-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_aufgabe_neu_feedback_betrag_falsch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buchung',
            name='ersteller',
        ),
        migrations.RemoveField(
            model_name='buchung',
            name='freischaltung',
        ),
        migrations.AddField(
            model_name='buchung',
            name='betrag_korrekt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='buchung',
            name='konto_korrekt',
            field=models.IntegerField(choices=[(0, 'Richtig'), (1, 'Soll ist falsch'), (2, 'Haben ist falsch'), (3, 'Beide sind falsch')], default=0),
        ),
    ]
