# Generated by Django 5.1.1 on 2025-02-16 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_remove_buchung_ersteller_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buchung',
            name='ersteller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ersteller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buchung',
            name='freischaltung',
            field=models.DateField(blank=True, null=True),
        ),
    ]
