# Generated by Django 5.1.1 on 2025-02-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_buchung_ersteller_buchung_freischaltung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchung',
            name='betrag_korrekt',
            field=models.BooleanField(choices=[(0, 'Richtig'), (1, 'Soll ist falsch'), (2, 'Haben ist falsch'), (3, 'Beide sind falsch')], default=True),
        ),
    ]
