# Generated by Django 5.1.1 on 2025-02-16 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_alter_buchung_betrag_korrekt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='aufgabe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.aufgabe_neu'),
        ),
    ]
