# Generated by Django 5.1.1 on 2025-02-16 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_alter_mail_aufgabe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anfangsbestand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betrag', models.FloatField()),
                ('konto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anfangsbestände', to='posts.konto')),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anfangsbestände', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nutzer', 'konto')},
            },
        ),
    ]
