# Generated by Django 5.1.1 on 2025-02-19 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_anfangsbestand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe_neu',
            name='anschrift_kunde',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aufgabe_neu',
            name='datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aufgabe_neu',
            name='eigene_ansicht',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aufgabe_neu',
            name='kontakt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aufgabe_neu',
            name='rechnungsbetrag',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aufgabe_neu',
            name='rechnungsnummer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aufgabe_neu',
            name='rechnungstyp',
            field=models.CharField(choices=[('eingehend', 'Eingehende Rechnung'), ('ausgehend', 'Ausgehende Rechnung'), ('intern', 'Interner Vorgang')], default='intern', max_length=20),
        ),
        migrations.AddField(
            model_name='aufgabe_neu',
            name='verabschiedung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aufgabe_neu',
            name='zahlweise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anfangsbestand',
            name='konto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anfangsbestaende', to='posts.konto'),
        ),
        migrations.AlterField(
            model_name='anfangsbestand',
            name='nutzer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anfangsbestaende', to=settings.AUTH_USER_MODEL),
        ),
    ]
