# Generated by Django 5.1.1 on 2025-02-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_aufgabe_neu_anschrift_kunde_aufgabe_neu_datum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe_neu',
            name='beschreibung',
            field=models.TextField(blank=True, default='Keine weiteren Details angegeben.', null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='anschrift_kunde',
            field=models.TextField(blank=True, default='Kunde XYZ\nMusterstraße 1\n12345 Musterstadt', null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='datum',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='eigene_ansicht',
            field=models.TextField(blank=True, default='Mein Unternehmen GmbH\nHauptstraße 10\n54321 Stadt', null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='kontakt',
            field=models.TextField(blank=True, default='Tel: 01234 567890\nE-Mail: info@unternehmen.de', null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='rechnungsbetrag',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='rechnungsnummer',
            field=models.CharField(blank=True, default='RE-00001', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='verabschiedung',
            field=models.TextField(blank=True, default='Mit freundlichen Grüßen,\nIhr Unternehmen', null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='zahlweise',
            field=models.CharField(blank=True, default='Überweisung innerhalb von 14 Tagen', max_length=255, null=True),
        ),
    ]
