# Generated by Django 5.1.1 on 2025-02-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_aufgabe_neu_beschreibung_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutzeraufgabe',
            name='betrag',
        ),
        migrations.RemoveField(
            model_name='nutzeraufgabe',
            name='haben_konto',
        ),
        migrations.RemoveField(
            model_name='nutzeraufgabe',
            name='soll_konto',
        ),
        migrations.AddField(
            model_name='nutzeraufgabe',
            name='haben_betraege',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='nutzeraufgabe',
            name='haben_konten',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='nutzeraufgabe',
            name='soll_betraege',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='nutzeraufgabe',
            name='soll_konten',
            field=models.JSONField(default=list),
        ),
    ]
