# Generated by Django 5.1.1 on 2025-02-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_remove_nutzeraufgabe_betrag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabedetail',
            name='bezugs_konten',
            field=models.ManyToManyField(blank=True, related_name='abhaengige_konten', to='posts.aufgabedetail'),
        ),
        migrations.AddField(
            model_name='aufgabedetail',
            name='faktor',
            field=models.FloatField(blank=True, help_text='Multiplikationsfaktor, falls abhängig von einem anderen Konto', null=True),
        ),
        migrations.AddField(
            model_name='aufgabedetail',
            name='festbetrag',
            field=models.FloatField(blank=True, help_text='Fester Betrag, falls kein Bezugskonto genutzt wird', null=True),
        ),
        migrations.AddField(
            model_name='aufgabedetail',
            name='formel_typ',
            field=models.CharField(choices=[('faktor', 'Multiplikation mit Faktor'), ('fix', 'Fester Betrag'), ('summe', 'Summe aus mehreren Konten')], default='fix', max_length=50),
        ),
        migrations.AlterField(
            model_name='aufgabedetail',
            name='betrag',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
