# Generated by Django 5.1.1 on 2025-02-26 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_aufgabedetail_bezugs_konten_aufgabedetail_faktor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufgabedetail',
            name='bezugs_konten',
        ),
        migrations.AddField(
            model_name='aufgabedetail',
            name='bezugs_konto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faktor_quellen', to='posts.aufgabedetail'),
        ),
    ]
