# Generated by Django 5.1.1 on 2025-02-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_remove_aufgabedetail_bezugs_konten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabedetail',
            name='bezugs_konto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
