# Generated by Django 5.1.1 on 2025-02-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_alter_aufgabedetail_bezugs_konto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('straße', models.CharField(max_length=255)),
                ('stadt', models.CharField(max_length=100)),
                ('plz', models.CharField(max_length=10)),
                ('telnr', models.IntegerField(max_length=10)),
            ],
        ),
    ]
