# Generated by Django 5.1.1 on 2025-02-27 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_absender'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe_neu',
            name='absender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.absender'),
        ),
        migrations.AddField(
            model_name='mail',
            name='absender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.absender'),
        ),
    ]
