# Generated by Django 5.1.1 on 2025-02-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_aufgabe_neu_absender_mail_absender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absender',
            name='telnr',
            field=models.IntegerField(null=True),
        ),
    ]
