# Generated by Django 5.1.1 on 2025-02-27 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_alter_absender_telnr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufgabe_neu',
            name='absender',
        ),
        migrations.AddField(
            model_name='nutzeraufgabe',
            name='absender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.absender'),
        ),
    ]
