# Generated by Django 5.1.1 on 2025-03-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_remove_aufgabe_neu_absender_nutzeraufgabe_absender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufgabe_neu',
            name='anschrift_kunde',
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='eigene_ansicht',
            field=models.TextField(blank=True, default='Secure Net\\Treskowallee 8\n10318 Berlin', null=True),
        ),
    ]
