# Generated by Django 5.1.1 on 2025-03-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_remove_aufgabe_neu_anschrift_kunde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe_neu',
            name='unterkategorie',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
