# Generated by Django 5.1.1 on 2025-03-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_aufgabe_neu_unterkategorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufgabe_neu',
            name='bezugswert',
        ),
    ]
