# Generated by Django 5.1.1 on 2025-03-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_remove_aufgabe_neu_bezugswert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufgabe_neu',
            name='max_wert',
        ),
        migrations.RemoveField(
            model_name='aufgabe_neu',
            name='min_wert',
        ),
    ]
