# Generated by Django 5.1.1 on 2025-03-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_remove_aufgabe_neu_max_wert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='frage',
            field=models.TextField(default='Dieses Feld kann gelöscht werden'),
        ),
    ]
