# Generated by Django 5.1.1 on 2025-03-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_alter_aufgabe_neu_frage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absender',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='eigene_ansicht',
            field=models.TextField(blank=True, default='Secure Net\nTreskowallee 8\n10318 Berlin', null=True),
        ),
    ]
