# Generated by Django 5.1.1 on 2025-03-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0039_alter_absender_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='verabschiedung',
            field=models.TextField(blank=True, default='Mit freundlichen Grüßen\nIhr Unternehmen', null=True),
        ),
    ]
