# Generated by Django 5.1.1 on 2025-03-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0040_alter_aufgabe_neu_verabschiedung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absender',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='absender',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='absender',
            name='plz',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='absender',
            name='stadt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='absender',
            name='straße',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
