# Generated by Django 5.1.1 on 2025-03-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0041_alter_absender_email_alter_absender_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchung',
            name='feedback_ollama',
            field=models.TextField(blank=True, null=True),
        ),
    ]
