# Generated by Django 5.1.1 on 2025-04-08 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0042_buchung_feedback_ollama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='konto',
            name='erstellt_von',
            field=models.ForeignKey(blank=True, help_text='Nutzer, der das Konto erstellt hat', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
