# Generated by Django 5.1.1 on 2025-04-08 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0043_konto_erstellt_von'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufgabedetail',
            name='kontoname',
        ),
        migrations.AddField(
            model_name='aufgabedetail',
            name='bezugs_konto_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aufgabedetail',
            name='konto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.konto'),
        ),
    ]
