# Generated by Django 5.1.1 on 2025-04-08 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0044_remove_aufgabedetail_kontoname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabedetail',
            name='bezugs_konto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verwendet_als_bezug', to='posts.konto'),
        ),
    ]
