# Generated by Django 5.1.1 on 2025-04-10 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0045_alter_aufgabedetail_bezugs_konto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='konto',
            name='kontenplan',
            field=models.IntegerField(default=1, help_text='Nummer des Kontenplans'),
        ),
        migrations.CreateModel(
            name='Kontenplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
