# Generated by Django 5.1.1 on 2025-04-10 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0046_konto_kontenplan_kontenplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konto',
            name='kontenplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.kontenplan'),
        ),
    ]
