# Generated by Django 5.1.1 on 2025-04-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0047_alter_konto_kontenplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='konto',
            name='bilanzposition_nummer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='konto',
            name='kontonummer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
