# Generated by Django 5.1.1 on 2025-04-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0048_konto_bilanzposition_nummer_konto_kontonummer'),
    ]

    operations = [
        migrations.AddField(
            model_name='unternehmen',
            name='fallstudie',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='unternehmen',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
