# Generated by Django 5.1.1 on 2025-04-14 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0049_unternehmen_fallstudie_alter_unternehmen_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='unternehmen',
            name='kontenplan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.kontenplan'),
            preserve_default=False,
        ),
    ]
