# Generated by Django 5.1.1 on 2025-04-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0050_unternehmen_kontenplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konto',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
