# Generated by Django 5.1.1 on 2025-04-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0051_alter_konto_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='fragentyp_text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
