# Generated by Django 5.1.1 on 2025-04-15 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0052_alter_aufgabe_neu_fragentyp_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='fragentyp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.aufgabenkategorie'),
        ),
    ]
