# Generated by Django 5.1.1 on 2025-04-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0053_alter_aufgabe_neu_fragentyp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='frage',
            field=models.TextField(default='Dieses Feld kann gelöscht werden', null=True),
        ),
    ]
