# Generated by Django 5.1.1 on 2025-04-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0054_alter_aufgabe_neu_frage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabedetail',
            name='bilanzposition',
            field=models.IntegerField(null=True),
        ),
    ]
