# Generated by Django 5.1.1 on 2025-04-17 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0055_aufgabedetail_bilanzposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabedetail',
            name='kontenplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.kontenplan'),
        ),
    ]
