# Generated by Django 5.1.1 on 2025-04-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0056_aufgabedetail_kontenplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe_neu',
            name='aufgabeninfo',
            field=models.TextField(blank=True, help_text='Optionaler Informationstext zur Aufgabe (HTML erlaubt).', null=True),
        ),
    ]
