# Generated by Django 5.1.1 on 2025-04-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0057_aufgabe_neu_aufgabeninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchung',
            name='original_konten_haben',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buchung',
            name='original_konten_soll',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
