# Generated by Django 5.1.1 on 2025-04-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0058_buchung_original_konten_haben_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe_neu',
            name='ersteller',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
