# Generated by Django 5.1.1 on 2025-04-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0059_aufgabe_neu_ersteller'),
    ]

    operations = [
        migrations.AddField(
            model_name='unternehmen',
            name='ersteller',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
