# Generated by Django 5.1.1 on 2025-05-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0060_unternehmen_ersteller'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe_neu',
            name='immer_feedback',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='zahlweise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
