# Generated by Django 5.1.1 on 2025-05-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0061_aufgabe_neu_immer_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufgabe_neu',
            name='immer_feedback',
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='rechnungstyp',
            field=models.CharField(choices=[('eingehend', 'Eingehende Rechnung'), ('ausgehend', 'Ausgehende Rechnung'), ('intern', 'Interner Vorgang'), ('non', 'Keine Rechnungsansicht')], default='intern', max_length=20),
        ),
    ]
