# Generated by Django 5.1.1 on 2025-05-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0062_remove_aufgabe_neu_immer_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe_neu',
            name='immer_feedback',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
