# Generated by Django 5.1.1 on 2025-05-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0063_aufgabe_neu_immer_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufgabedetail',
            name='bezugs_konto',
        ),
        migrations.RemoveField(
            model_name='aufgabedetail',
            name='bezugs_konto_alt',
        ),
        migrations.RemoveField(
            model_name='aufgabedetail',
            name='faktor',
        ),
        migrations.RemoveField(
            model_name='aufgabedetail',
            name='festbetrag',
        ),
        migrations.RemoveField(
            model_name='aufgabedetail',
            name='monat',
        ),
        migrations.RemoveField(
            model_name='aufgabedetail',
            name='monatsangabe',
        ),
    ]
