# Generated by Django 5.1.1 on 2025-05-26 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0064_remove_aufgabedetail_bezugs_konto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufgabedetail',
            name='formel_typ',
        ),
    ]
