# Generated by Django 5.1.1 on 2025-05-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0065_remove_aufgabedetail_formel_typ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufgabe_neu',
            name='frage',
        ),
    ]
