# Generated by Django 5.1.1 on 2025-06-02 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0066_remove_aufgabe_neu_frage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='eigene_ansicht',
            field=models.TextField(blank=True, default='Secure Net\nTreskowallee 8\n10318 Berlin', help_text='Feedback, wenn ein falsches Konto gewählt wurde.', null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='kontakt',
            field=models.TextField(blank=True, default='Tel: 01234 567890\nE-Mail: info@unternehmen.de', help_text='Feedback, wenn ein falsches Konto gewählt wurde.', null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='mailtext',
            field=models.TextField(help_text='Feedback, wenn ein falsches Konto gewählt wurde.'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='unterkategorie',
            field=models.IntegerField(blank=True, default=1, help_text='Feedback, wenn ein falsches Konto gewählt wurde.', null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='unternehmen_kategorie',
            field=models.ForeignKey(help_text='Feedback, wenn ein falsches Konto gewählt wurde.', on_delete=django.db.models.deletion.CASCADE, to='posts.unternehmen'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='verabschiedung',
            field=models.TextField(blank=True, default='Mit freundlichen Grüßen\nIhr Unternehmen', help_text='Feedback, wenn ein falsches Konto gewählt wurde.', null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='zahlweise',
            field=models.CharField(blank=True, help_text='Feedback, wenn ein falsches Konto gewählt wurde.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aufgabedetail',
            name='kontenplan',
            field=models.ForeignKey(blank=True, help_text='Feedback, wenn ein falsches Konto gewählt wurde.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.kontenplan'),
        ),
    ]
