# Generated by Django 5.1.1 on 2025-06-02 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0067_alter_aufgabe_neu_eigene_ansicht_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='eigene_ansicht',
            field=models.TextField(blank=True, default='Secure Net\nTreskowallee 8\n10318 Berlin', help_text='Angezeigter Text in der Mail, welche für die Nutzer verschickt wird. Zeigt die Addresse des eigenen Unternehmens', null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='feedback_betrag_falsch',
            field=models.TextField(blank=True, help_text='Ein allgemeines Feedback für eine falsche Lösung hinsichtlich des Betrages.', null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='feedback_konto_falsch',
            field=models.TextField(blank=True, help_text='Ein allgemeines Feedback für eine falsche Lösung hinsichtlich der ausgewählten Konten.', null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='fragentyp',
            field=models.ForeignKey(help_text='Der Aufgabentyp; Was für eine Art von Aufgabe liegt vor?', null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.aufgabenkategorie'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='kontakt',
            field=models.TextField(blank=True, default='Tel: 01234 567890\nE-Mail: info@unternehmen.de', help_text='Angezeigter Text in der Mail. Zeigt die Kontaktdaten des eigenen Unternehmens', null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='mailtext',
            field=models.TextField(help_text='Der angezeigte Text in der Mail, welchen die Nutzer für jede Aufgabe erhalten.'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='unterkategorie',
            field=models.IntegerField(blank=True, default=1, help_text='Feld für Unterteilung von Fragen mit dem selben Fragentyp', null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='unternehmen_kategorie',
            field=models.ForeignKey(help_text='Das Unternehmen oder die Fallstudie, zu welcher die Aufgabe zugeordnet wird.', on_delete=django.db.models.deletion.CASCADE, to='posts.unternehmen'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='verabschiedung',
            field=models.TextField(blank=True, default='Mit freundlichen Grüßen\nIhr Unternehmen', help_text='Angezeigter Text in der Mail. Zeigt die Verabschiedung. ', null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='zahlweise',
            field=models.CharField(blank=True, help_text='Auf welche Weise wird gezahlt? (Bar, Überweisung...)', max_length=255, null=True),
        ),
    ]
