# Generated by Django 5.1.1 on 2025-06-05 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0068_alter_aufgabe_neu_eigene_ansicht_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='absender',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='absender',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='absender',
            name='plz',
            field=models.CharField(max_length=10, null=True, verbose_name='Plz'),
        ),
        migrations.AlterField(
            model_name='absender',
            name='stadt',
            field=models.CharField(max_length=100, null=True, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='absender',
            name='straße',
            field=models.CharField(max_length=255, null=True, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='absender',
            name='telnr',
            field=models.IntegerField(null=True, verbose_name='telnr'),
        ),
        migrations.AlterField(
            model_name='anfangsbestand',
            name='betrag',
            field=models.FloatField(verbose_name='Betrag'),
        ),
        migrations.AlterField(
            model_name='anfangsbestand',
            name='konto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anfangsbestaende', to='posts.konto', verbose_name='Konto'),
        ),
        migrations.AlterField(
            model_name='anfangsbestand',
            name='nutzer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anfangsbestaende', to=settings.AUTH_USER_MODEL, verbose_name='Nutzer'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='aufgabeninfo',
            field=models.TextField(blank=True, help_text='Optionaler Informationstext zur Aufgabe (HTML erlaubt).', null=True, verbose_name='Aufgabeninfo'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='beschreibung',
            field=models.TextField(blank=True, default='Keine weiteren Details angegeben.', null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='datum',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='eigene_ansicht',
            field=models.TextField(blank=True, default='Secure Net\nTreskowallee 8\n10318 Berlin', help_text='Angezeigter Text in der Mail, welche für die Nutzer verschickt wird. Zeigt die Addresse des eigenen Unternehmens', null=True, verbose_name='Eigene Ansicht'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='ersteller',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ersteller'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='feedback_betrag_falsch',
            field=models.TextField(blank=True, help_text='Ein allgemeines Feedback für eine falsche Lösung hinsichtlich des Betrages.', null=True, verbose_name='Feedback Betrag falsch'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='feedback_konto_falsch',
            field=models.TextField(blank=True, help_text='Ein allgemeines Feedback für eine falsche Lösung hinsichtlich der ausgewählten Konten.', null=True, verbose_name='Feedback Konto falsch'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='fragentyp',
            field=models.ForeignKey(help_text='Der Aufgabentyp; Was für eine Art von Aufgabe liegt vor?', null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.aufgabenkategorie', verbose_name='Fragentyp'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='immer_feedback',
            field=models.BooleanField(blank=True, null=True, verbose_name='immer Feedback'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='kontakt',
            field=models.TextField(blank=True, default='Tel: 01234 567890\nE-Mail: info@unternehmen.de', help_text='Angezeigter Text in der Mail. Zeigt die Kontaktdaten des eigenen Unternehmens', null=True, verbose_name='Kontakt'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='mailtext',
            field=models.TextField(help_text='Der angezeigte Text in der Mail, welchen die Nutzer für jede Aufgabe erhalten.', verbose_name='Mailtext'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='nutzungsdauer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nutzungsdauer'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='rechnungsbetrag',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Rechnungsbetrag'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='rechnungsnummer',
            field=models.CharField(blank=True, default='RE-00001', max_length=50, null=True, verbose_name='Rechnungsnummer'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='rechnungstyp',
            field=models.CharField(choices=[('eingehend', 'Eingehende Rechnung'), ('ausgehend', 'Ausgehende Rechnung'), ('intern', 'Interner Vorgang'), ('non', 'Keine Rechnungsansicht')], default='intern', max_length=20, verbose_name='Rechnungstyp'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='unterkategorie',
            field=models.IntegerField(blank=True, default=1, help_text='Feld für Unterteilung von Fragen mit dem selben Fragentyp', null=True, verbose_name='Unterkategorie'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='unternehmen_kategorie',
            field=models.ForeignKey(help_text='Das Unternehmen oder die Fallstudie, zu welcher die Aufgabe zugeordnet wird.', on_delete=django.db.models.deletion.CASCADE, to='posts.unternehmen', verbose_name='Unternehmen Kategorie'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='verabschiedung',
            field=models.TextField(blank=True, default='Mit freundlichen Grüßen\nIhr Unternehmen', help_text='Angezeigter Text in der Mail. Zeigt die Verabschiedung. ', null=True, verbose_name='Verabschiedung'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='zahlweise',
            field=models.CharField(blank=True, help_text='Auf welche Weise wird gezahlt? (Bar, Überweisung...)', max_length=255, null=True, verbose_name='Zahlweise'),
        ),
        migrations.AlterField(
            model_name='aufgabedetail',
            name='aufgabe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='posts.aufgabe_neu', verbose_name='Aufgabe'),
        ),
        migrations.AlterField(
            model_name='aufgabedetail',
            name='betrag',
            field=models.FloatField(blank=True, null=True, verbose_name='Betrag'),
        ),
        migrations.AlterField(
            model_name='aufgabedetail',
            name='bilanzposition',
            field=models.IntegerField(null=True, verbose_name='Bilanzposition'),
        ),
        migrations.AlterField(
            model_name='aufgabedetail',
            name='kontenplan',
            field=models.ForeignKey(blank=True, help_text='Feedback, wenn ein falsches Konto gewählt wurde.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.kontenplan', verbose_name='Kontenplan'),
        ),
        migrations.AlterField(
            model_name='aufgabedetail',
            name='konto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.konto', verbose_name='Konto'),
        ),
        migrations.AlterField(
            model_name='aufgabedetail',
            name='soll_haben',
            field=models.CharField(choices=[('Soll', 'Soll'), ('Haben', 'Haben')], max_length=50, verbose_name='Soll/Haben'),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='abgeschlossen_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Abgeschlossen Datum'),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='antwort_betrag_haben',
            field=models.JSONField(blank=True, null=True, verbose_name='Antwort Betrag Haben'),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='antwort_betrag_soll',
            field=models.JSONField(blank=True, null=True, verbose_name='Antwort Betrag Soll'),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='antwort_konten_haben',
            field=models.JSONField(blank=True, null=True, verbose_name='Antwort Konten Haben'),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='antwort_konten_soll',
            field=models.JSONField(blank=True, null=True, verbose_name='Antwort Konten Soll'),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='aufgabe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.aufgabe_neu', verbose_name='Aufgabe'),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='betrag_korrekt',
            field=models.IntegerField(choices=[(0, 'Richtig'), (1, 'Soll ist falsch'), (2, 'Haben ist falsch'), (3, 'Beide sind falsch')], default=True, verbose_name='Betrag Korrekt'),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='buchung_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Buchungs ID'),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='ersteller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ersteller', to=settings.AUTH_USER_MODEL, verbose_name='Ersteller'),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='feedback_ollama',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback Ollama'),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='freischaltung',
            field=models.DateField(blank=True, null=True, verbose_name='Freischaltung'),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='konto_korrekt',
            field=models.IntegerField(choices=[(0, 'Richtig'), (1, 'Soll ist falsch'), (2, 'Haben ist falsch'), (3, 'Beide sind falsch')], default=0, verbose_name='Konto Korrekt'),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='korrekturbuchung',
            field=models.BooleanField(default=False, verbose_name='Korrekturbuchung'),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='nutzer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nutzer'),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='original_konten_haben',
            field=models.JSONField(blank=True, null=True, verbose_name='Original Konten Haben'),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='original_konten_soll',
            field=models.JSONField(blank=True, null=True, verbose_name='Original Konten Soll'),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='status',
            field=models.CharField(choices=[('offen', 'Offen'), ('bearbeitet', 'Bearbeitet'), ('korrekt', 'Korrekt')], default='offen', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='versuch',
            field=models.PositiveIntegerField(default=1, verbose_name='Versuch'),
        ),
        migrations.AlterField(
            model_name='kontenplan',
            name='nutzer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nutzer'),
        ),
        migrations.AlterField(
            model_name='konto',
            name='bilanzposition_nummer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bilanzposition Nummer'),
        ),
        migrations.AlterField(
            model_name='konto',
            name='eins',
            field=models.CharField(blank=True, choices=[('Aktiva', 'Aktiva'), ('Passiva', 'Passiva'), ('Aufwand', 'Aufwand'), ('Ertrag', 'Ertrag')], max_length=20, null=True, verbose_name='eins'),
        ),
        migrations.AlterField(
            model_name='konto',
            name='erstellt_von',
            field=models.ForeignKey(blank=True, help_text='Nutzer, der das Konto erstellt hat', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AlterField(
            model_name='konto',
            name='kategorie',
            field=models.CharField(blank=True, choices=[('Bestandskonto', 'Bestandskonto'), ('Erfolgskonto', 'Erfolgskonto')], max_length=20, null=True, verbose_name='kategorie'),
        ),
        migrations.AlterField(
            model_name='konto',
            name='kontenplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.kontenplan', verbose_name='Kontenplan'),
        ),
        migrations.AlterField(
            model_name='konto',
            name='kontonummer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kontonummer'),
        ),
        migrations.AlterField(
            model_name='konto',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='konto',
            name='unterkategorie',
            field=models.CharField(blank=True, choices=[('Aktiva', 'Aktiva'), ('Passiva', 'Passiva'), ('Aufwand', 'Aufwand'), ('Ertrag', 'Ertrag')], max_length=20, null=True, verbose_name='Unterkategorie'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='absender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.absender', verbose_name='Absender'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='absender_adresse',
            field=models.CharField(default='', max_length=255, verbose_name='Absender Adresse'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='absender_name',
            field=models.CharField(default='', max_length=100, verbose_name='Absender Name'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='aufgabe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.aufgabe_neu', verbose_name='Aufgabe'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='betreff',
            field=models.CharField(max_length=255, verbose_name='Betreff'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='datum',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mailtext',
            field=models.TextField(verbose_name='Mailtext'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='nutzer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nutzer'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='versuch',
            field=models.PositiveIntegerField(default=1, verbose_name='Versuch'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='von',
            field=models.CharField(default='system@secure-net.de', max_length=100, verbose_name='Von'),
        ),
        migrations.AlterField(
            model_name='nutzeraufgabe',
            name='absender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.absender', verbose_name='Absender'),
        ),
        migrations.AlterField(
            model_name='nutzeraufgabe',
            name='aufgabe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.aufgabe_neu', verbose_name='Aufgabe'),
        ),
        migrations.AlterField(
            model_name='nutzeraufgabe',
            name='bearbeitungsstand',
            field=models.CharField(choices=[('offen', 'Offen'), ('bearbeitet', 'Bearbeitet'), ('korrekt', 'Korrekt')], default='offen', max_length=20, verbose_name='Bearbeitungsstand'),
        ),
        migrations.AlterField(
            model_name='nutzeraufgabe',
            name='erstellt_am',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='nutzeraufgabe',
            name='haben_betraege',
            field=models.JSONField(default=list, verbose_name='Haben Beträge'),
        ),
        migrations.AlterField(
            model_name='nutzeraufgabe',
            name='haben_konten',
            field=models.JSONField(default=list, verbose_name='Haben Konten'),
        ),
        migrations.AlterField(
            model_name='nutzeraufgabe',
            name='nutzer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nutzer'),
        ),
        migrations.AlterField(
            model_name='nutzeraufgabe',
            name='soll_betraege',
            field=models.JSONField(default=list, verbose_name='Soll Beträge'),
        ),
        migrations.AlterField(
            model_name='nutzeraufgabe',
            name='soll_konten',
            field=models.JSONField(default=list, verbose_name='Soll Konten'),
        ),
        migrations.AlterField(
            model_name='unternehmen',
            name='ersteller',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ersteller'),
        ),
        migrations.AlterField(
            model_name='unternehmen',
            name='fallstudie',
            field=models.BooleanField(default=0, verbose_name='Fallstudie'),
        ),
        migrations.AlterField(
            model_name='unternehmen',
            name='kontenplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.kontenplan', verbose_name='kontenplan'),
        ),
        migrations.AlterField(
            model_name='unternehmen',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
