# Generated by Django 5.1.1 on 2025-06-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0069_alter_absender_email_alter_absender_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontenplan',
            name='sprache',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
