# Generated by Django 5.1.1 on 2025-06-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0070_kontenplan_sprache'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe_neu',
            name='beschreibung_de',
            field=models.TextField(blank=True, default='Keine weiteren Details angegeben.', null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='aufgabe_neu',
            name='beschreibung_en',
            field=models.TextField(blank=True, default='No further details.', null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='aufgabe_neu',
            name='mailtext_de',
            field=models.TextField(help_text='Der angezeigte Text in der Mail, welchen die Nutzer für jede Aufgabe erhalten.', null=True, verbose_name='Mailtext'),
        ),
        migrations.AddField(
            model_name='aufgabe_neu',
            name='mailtext_en',
            field=models.TextField(help_text='Der angezeigte Text in der Mail, welchen die Nutzer für jede Aufgabe erhalten.', null=True, verbose_name='Mailtext'),
        ),
        migrations.AddField(
            model_name='aufgabe_neu',
            name='verabschiedung_de',
            field=models.TextField(blank=True, default='Mit freundlichen Grüßen\nIhr Unternehmen', help_text='Angezeigter Text in der Mail. Zeigt die Verabschiedung. ', null=True, verbose_name='Verabschiedung'),
        ),
        migrations.AddField(
            model_name='aufgabe_neu',
            name='verabschiedung_en',
            field=models.TextField(blank=True, default='With regards\nYour Business', help_text='Angezeigter Text in der Mail. Zeigt die Verabschiedung. ', null=True, verbose_name='Verabschiedung'),
        ),
        migrations.AddField(
            model_name='mail',
            name='betreff_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Betreff'),
        ),
        migrations.AddField(
            model_name='mail',
            name='betreff_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Betreff'),
        ),
        migrations.AddField(
            model_name='mail',
            name='mailtext_de',
            field=models.TextField(null=True, verbose_name='Mailtext'),
        ),
        migrations.AddField(
            model_name='mail',
            name='mailtext_en',
            field=models.TextField(null=True, verbose_name='Mailtext'),
        ),
    ]
