# Generated by Django 5.1.1 on 2025-06-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0071_aufgabe_neu_beschreibung_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe_neu',
            name='umsatzsteuerfrei',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
