# Generated by Django 5.1.1 on 2025-06-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0072_aufgabe_neu_umsatzsteuerfrei'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutzeraufgabe',
            name='leistungszeitraum_anfang',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutzeraufgabe',
            name='leistungszeitraum_ende',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='eigene_ansicht',
            field=models.TextField(blank=True, default='SecureNet\nTreskowallee 8\n10318 Berlin', help_text='Angezeigter Text in der Mail, welche für die Nutzer verschickt wird. Zeigt die Addresse des eigenen Unternehmens', null=True, verbose_name='Eigene Ansicht'),
        ),
    ]
