# Generated by Django 5.1.1 on 2025-06-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0073_nutzeraufgabe_leistungszeitraum_anfang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe_neu',
            name='hat_leistugnszeitraum',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
