# Generated by Django 5.1.1 on 2025-06-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0074_aufgabe_neu_hat_leistugnszeitraum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aufgabe_neu',
            old_name='hat_leistugnszeitraum',
            new_name='hat_leistungszeitraum',
        ),
    ]
