# Generated by Django 5.1.1 on 2025-06-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0075_rename_hat_leistugnszeitraum_aufgabe_neu_hat_leistungszeitraum'),
    ]

    operations = [
        migrations.AddField(
            model_name='konto',
            name='hat_anfangsbestand',
            field=models.BooleanField(default=False),
        ),
    ]
