# Generated by Django 5.1.1 on 2025-06-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0076_konto_hat_anfangsbestand'),
    ]

    operations = [
        migrations.AddField(
            model_name='konto',
            name='anfangsbestand_menge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
