# Generated by Django 5.1.1 on 2025-06-26 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0077_konto_anfangsbestand_menge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='hat_leistungszeitraum',
            field=models.BooleanField(blank=True, default=0, help_text='Zeigt im Dokument den Leistungszeitraum an.', null=True, verbose_name='Hat Leistungszeitraum'),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='umsatzsteuerfrei',
            field=models.BooleanField(blank=True, default=0, help_text='Zeigt im Dokument an, dass der Betrag steuerfrei ist.', null=True),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='aufgabe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.aufgabe_neu', verbose_name='Aufgabe'),
        ),
        migrations.AlterField(
            model_name='buchung',
            name='status',
            field=models.CharField(choices=[('offen', 'Offen'), ('bearbeitet', 'Bearbeitet'), ('korrekt', 'Korrekt')], default='offen', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
