# Generated by Django 5.1.1 on 2025-06-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0078_alter_aufgabe_neu_hat_leistungszeitraum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unternehmen',
            name='anzeigename',
            field=models.CharField(blank=True, default=models.CharField(max_length=100, verbose_name='Name'), max_length=100, null=True),
        ),
    ]
