# Generated by Django 5.1.1 on 2025-07-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0079_unternehmen_anzeigename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unternehmen',
            name='anzeigename',
            field=models.CharField(blank=True, default='SecureNet', max_length=100, null=True),
        ),
    ]
