# Generated by Django 5.1.1 on 2025-07-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0080_alter_unternehmen_anzeigename'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutzeraufgabe',
            name='rn_nummer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='rechnungstyp',
            field=models.CharField(choices=[('eingehend', 'Eingehende Rechnung'), ('ausgehend', 'Ausgehende Rechnung'), ('intern', 'Interner Vorgang'), ('non', 'Keine Rechnungsansicht')], default='intern', help_text='Soll die Aufgabe als Rechnung dargetellt werden? (Eingehend = wir erhalten; Ausgehen = wir stellen eine aus; Intern = Es liegt keine Rechnung für den Geschäftsvorfall z.B. Abschreibungen; Keine = Nur die unten beigefügte Beschreibung und Beträge werden angezeigt)', max_length=20, verbose_name='Rechnungstyp'),
        ),
    ]
