# Generated by Django 5.1.1 on 2025-07-21 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0081_nutzeraufgabe_rn_nummer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbackbereich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('von_betrag', models.FloatField(verbose_name='Von Betrag')),
                ('bis_betrag', models.FloatField(verbose_name='Bis Betrag')),
                ('feedback_text', models.TextField(verbose_name='Feedbacktext')),
                ('aufgabe_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbackbereiche', to='posts.aufgabedetail', verbose_name='Zugehöriger Buchungssatz')),
            ],
        ),
    ]
