# Generated by Django 5.1.1 on 2025-07-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0082_feedbackbereich'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutzeraufgabe',
            name='faktor',
            field=models.FloatField(default=1.0, verbose_name='Skalierungsfaktor'),
        ),
    ]
