# Generated by Django 5.1.1 on 2025-07-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0083_nutzeraufgabe_faktor'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchung',
            name='feedback_bereiche_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
