# Generated by Django 5.1.1 on 2025-07-21 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0084_buchung_feedback_bereiche_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackbereich',
            name='konto_falsch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_falsch_konto', to='posts.konto'),
        ),
    ]
