# Generated by Django 5.1.1 on 2025-07-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0085_feedbackbereich_konto_falsch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackbereich',
            name='bis_betrag',
            field=models.FloatField(blank=True, null=True, verbose_name='Bis Betrag'),
        ),
        migrations.AlterField(
            model_name='feedbackbereich',
            name='konto_falsch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackbereich',
            name='von_betrag',
            field=models.FloatField(blank=True, null=True, verbose_name='Von Betrag'),
        ),
    ]
