# Generated by Django 5.1.1 on 2025-07-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0086_alter_feedbackbereich_bis_betrag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackbereich',
            name='konto_falsch',
        ),
    ]
