# Generated by Django 5.1.1 on 2025-07-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0087_remove_feedbackbereich_konto_falsch'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackbereich',
            name='konto_falsch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
