# Generated by Django 5.1.1 on 2025-07-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0089_rename_konto_falsch_feedbackbereich_konto_falsch_alt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackbereich',
            old_name='konto_falsch_alt',
            new_name='konto_falsch',
        ),
    ]
