# Generated by Django 5.1.1 on 2025-08-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0090_rename_konto_falsch_alt_feedbackbereich_konto_falsch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='fragentyp_text',
            field=models.CharField(max_length=255, null=True, verbose_name='Mailbetreff Geschäftsvorfall'),
        ),
    ]
