# Generated by Django 5.1.1 on 2025-08-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0091_alter_aufgabe_neu_fragentyp_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabenkategorie',
            name='ersteller',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ersteller'),
        ),
    ]
