# Generated by Django 5.1.1 on 2025-08-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0092_aufgabenkategorie_ersteller'),
    ]

    operations = [
        migrations.AddField(
            model_name='konto',
            name='steuerkonto',
            field=models.IntegerField(choices=[(0, 'kein Steuerkonto'), (1, 'Vorsteuer'), (2, 'Umsatzsteuer')], default=0, verbose_name='Steuerkonto'),
        ),
    ]
