# Generated by Django 5.1.1 on 2025-08-27 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0093_konto_steuerkonto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe_neu',
            name='eigene_ansicht',
            field=models.TextField(blank=True, help_text='Angezeigter Text in der Mail, welche für die Nutzer verschickt wird. Zeigt die Addresse des eigenen Unternehmens', null=True, verbose_name='Eigene Ansicht'),
        ),
        migrations.CreateModel(
            name='NutzerAbschluss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('GUV', 'GuV'), ('BILANZ', 'Bilanz')], max_length=10)),
                ('daten', models.JSONField(default=dict)),
                ('korrekt', models.BooleanField(blank=True, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nutzer', 'typ')},
            },
        ),
    ]
