# Generated by Django 5.1.1 on 2025-08-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0094_alter_aufgabe_neu_eigene_ansicht_nutzerabschluss'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutzerabschluss',
            name='eingabe',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
