# Generated by Django 5.1.1 on 2025-08-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0095_nutzerabschluss_eingabe'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutzerabschluss',
            name='dynamik',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='konto',
            name='eins',
            field=models.CharField(blank=True, choices=[('Aktiva', 'Aktiva'), ('Passiva', 'Passiva'), ('Aufwand', 'Aufwand'), ('Ertrag', 'Ertrag'), ('DYNAMIK_ERFOLG', 'Dynamisch (GuV)'), ('DYNAMIK_BESTAND', 'Dynamisch (Bilanz)')], max_length=20, null=True, verbose_name='eins'),
        ),
        migrations.AlterField(
            model_name='konto',
            name='steuerkonto',
            field=models.IntegerField(blank=True, choices=[(0, 'kein Steuerkonto'), (1, 'Vorsteuer'), (2, 'Umsatzsteuer')], default=0, null=True, verbose_name='Steuerkonto'),
        ),
        migrations.AlterField(
            model_name='konto',
            name='unterkategorie',
            field=models.CharField(blank=True, choices=[('Aktiva', 'Aktiva'), ('Passiva', 'Passiva'), ('Aufwand', 'Aufwand'), ('Ertrag', 'Ertrag'), ('DYNAMIK_ERFOLG', 'Dynamisch (GuV)'), ('DYNAMIK_BESTAND', 'Dynamisch (Bilanz)')], max_length=20, null=True, verbose_name='Unterkategorie'),
        ),
    ]
