# Generated by Django 5.1.1 on 2024-10-28 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studiengang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='semester',
            field=models.CharField(choices=[('WS 24/25', 'WS 24/25'), ('SS 25', 'SS 25'), ('WS 25/26', 'WS 25/26'), ('SS 26', 'SS 26'), ('WS 26/27', 'WS 26/27')], default='WS 24/25', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='studiengang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.studiengang'),
        ),
    ]
