# Generated by Django 5.1.1 on 2024-10-28 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studiengang_customuser_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='studiengang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='users.studiengang'),
        ),
    ]
