# Generated by Django 5.1.1 on 2025-03-02 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_remove_aufgabe_neu_absender_nutzeraufgabe_absender'),
        ('users', '0003_customuser_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unternehmen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studierende', to='posts.unternehmen'),
        ),
    ]
