# Generated by Django 5.1.1 on 2025-03-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_unternehmen'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nutzergruppe',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
