# Generated by Django 5.1.1 on 2024-10-29 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='semester',
        ),
        migrations.AddField(
            model_name='customuser',
            name='semester_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.semester'),
        ),
    ]
