# Generated by Django 5.1.1 on 2025-04-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_nutzergruppe'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='ersteller',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studiengang',
            name='ersteller',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
