# Generated by Django 5.1.1 on 2024-10-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_semester_customuser_semester_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='semester_id',
            new_name='semester',
        ),
    ]
