# Generated by Django 5.1.1 on 2024-10-17 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studierenderprofile',
            name='lehrkraft',
        ),
        migrations.RemoveField(
            model_name='studierenderprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.CreateModel(
            name='Lehrkraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Studierender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lehrkraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studierende', to='users.lehrkraft')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LehrkraftProfile',
        ),
        migrations.DeleteModel(
            name='StudierenderProfile',
        ),
    ]
