# Generated by Django 5.1.1 on 2024-10-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_studierenderprofile_lehrkraft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lehrkraft',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studierender',
            name='lehrkraft',
        ),
        migrations.RemoveField(
            model_name='studierender',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Lehrkraft',
        ),
        migrations.DeleteModel(
            name='Studierender',
        ),
    ]
