# Generated by Django 5.1.1 on 2025-06-05 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0069_alter_absender_email_alter_absender_name_and_more'),
        ('users', '0006_semester_ersteller_studiengang_ersteller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Anzeigename'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nutzergruppe',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nutzergruppe'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='professor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='semester',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.semester', verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='studiengang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='users.studiengang', verbose_name='Studiengang'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unternehmen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studierende', to='posts.unternehmen', verbose_name='Unternehmen'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='ersteller',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ersteller'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='studiengang',
            name='ersteller',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ersteller'),
        ),
        migrations.AlterField(
            model_name='studiengang',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
