# Generated by Django 5.1.1 on 2024-10-29 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='semester',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.semester'),
        ),
    ]
