# Generated by Django 5.1.1 on 2024-10-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_customuser_role_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lehrkraft',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studierender',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studierender',
            name='lehrkraft',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Lehrkraft',
        ),
        migrations.DeleteModel(
            name='Studierender',
        ),
    ]
