# Generated by Django 5.1.1 on 2024-10-21 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_initial'),
    ]

    operations = [
    ]
